apiVersion: v1
appVersion: v0.5.0
description: Longhorn is a distributed block storage system for Kubernetes powered
  by Rancher Labs.
home: https://github.com/rancher/longhorn
icon: https://s3.us-east-2.amazonaws.com/longhorn-assets/longhorn-logo.svg
keywords:
- longhorn
- storage
- distributed
- block
- device
- iscsi
kubeVersion: '>=v1.8.0-r0'
maintainers:
- email: charts@rancher.com
  name: rancher
name: longhorn
sources:
- https://github.com/rancher/longhorn
- https://github.com/rancher/longhorn-engine
- https://github.com/rancher/longhorn-manager
- https://github.com/rancher/longhorn-ui
- https://github.com/rancher/longhorn-tests
version: 0.5.0
