{{- if eq .Values.tls "ingress" -}}
  {{- if eq .Values.ingress.tls.source "cubepaas" -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ template "cubepaas.fullname" . }}
  labels:
    app: {{ template "cubepaas.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ca:
    secretName: tls-cubepaas
  {{- end -}}
{{- end -}}
